//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_Software.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeesCourses = new HashSet<EmployeesCours>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int PositionId { get; set; }
        public int DepatmentId { get; set; }
        public int ContactDataId { get; set; }
    
        public virtual ContactData ContactData { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeesCours> EmployeesCourses { get; set; }
        public virtual Position Position { get; set; }
        public virtual Employment Employment { get; set; }
        public virtual Moving Moving { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual Termination Termination { get; set; }
        public virtual Vacation Vacation { get; set; }
        public virtual WorkHour WorkHour { get; set; }
    }
}
