//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_Software.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactData> ContactDatas { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeesCours> EmployeesCourses { get; set; }
        public virtual DbSet<Employment> Employments { get; set; }
        public virtual DbSet<Moving> Movings { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Response> Responses { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Termination> Terminations { get; set; }
        public virtual DbSet<Vacancy> Vacancies { get; set; }
        public virtual DbSet<Vacation> Vacations { get; set; }
        public virtual DbSet<WorkHour> WorkHours { get; set; }
    }
}
