//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_Software.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moving
    {
        public int EmployeeId { get; set; }
        public int PreviousPosition { get; set; }
        public int NewPosition { get; set; }
        public int PreviousDepartment { get; set; }
        public int NewDepartment { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Position Position { get; set; }
        public virtual Position Position1 { get; set; }
    }
}
