//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_Software.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public int Id { get; set; }
        public int VacancyId { get; set; }
        public int ContactDataId { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
    
        public virtual ContactData ContactData { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
